version: '2.4'

services:
  react_native_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.88.207
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    volumes:
      - ./:/opt/GUINativeChat/app
    healthcheck:
      disable: true

volumes:
  notused: